//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoAgili
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dishes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dishes()
        {
            this.Pedido = new HashSet<Pedido>();
            this.IngredientOnAPlate = new HashSet<IngredientOnAPlate>();
        }
    
        public int IdDish { get; set; }
        public string Name { get; set; }
        public int IdRestaurant { get; set; }
        public double Price { get; set; }
        public byte[] Photo { get; set; }
        public bool IsOnMenu { get; set; }
        public string Description { get; set; }
        public Nullable<int> IdCategory { get; set; }
    
        public virtual Restaurants Restaurants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido> Pedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngredientOnAPlate> IngredientOnAPlate { get; set; }
        public virtual Category Category { get; set; }
    }
}
