//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoAgili
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public int IdPedido { get; set; }
        public int IdUser { get; set; }
        public int IdDish { get; set; }
        public System.DateTime Date { get; set; }
        public double Price { get; set; }
    
        public virtual Dishes Dishes { get; set; }
        public virtual Users Users { get; set; }
    }
}
